### PR TITLE
Added menu-popup on mobile mode

### PR DESCRIPTION
**Pull request by FireQueen-3010**
image
(styling not added yet)

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia :)

**Review by LordShenron — APPROVED** [review]
Works fine in my testing.

**Comment by LordShenron** [comment]
@ArunTeltia I have merged it but there is one thing i noticed. How in the seven heaven any first time user is supposed to know that tapping the logo icon will open the side navbar xD

**Comment by ArunTeltia** [comment]
Okay so you have installed some dependency which is not in the package.json because of that the repo is breaking

**Comment by LordShenron** [comment]
> Okay so you have installed some dependency which is not in the package.json because of that the repo is breaking

Fix karo maharaj xD

**Pull request merged**
